# Keep consistent with https://github.com/keroro520/ansible-ckb/blob/master/defaults/main.yml
# ckb_sync_target_number: 10
ckb_workspace: "/home/ckb/gp/sync/node1"
ckb_service: sync_ckb_node1
ckb_data_dir: "{{ ckb_workspace }}/data"
ckb_rpc_listen_address: "0.0.0.0:8010"
ckb_chain_spec_file: "sync-spec.toml"
ckb_network_listen_addresses: ["/ip4/0.0.0.0/tcp/8050"]
ckb_miner_poll_interval: 1000
ckb_data_local_source: "ckb-prepare-data/big-tx/data.tar.gz"

# ansible-ckb miner variables
ckb_block_assembler:
  key: "98400f6a67af07025f5959af35ed653d649f745b8f54bf3f07bef9bd605ee946"
  code_hash: "0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8"
  args: "0x8883a512ee2383c01574a328f60eeccbb4d78240"
  hash_type: "type"
  message: "0x"