[package]
name = "sync-chart"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plotters = { version = "0.3.1", features = ["datetime"] }
chrono = "0.4.19"
