---
- hosts: "{{ hostname }}"
  gather_facts: yes
  tasks:
    - include_vars: vars/all.yml
      tags: [ always ]
    - name: Operate CKB Via Ansible-CKB
      include_role:
        name: ansible-ckb
        public: false
      tags:
        - ckb_install
        - ckb_configure
        - ckb_restart
        - ckb_start
        - ckb_stop
        - ckb_status
        - ckb_miner_restart
        - ckb_miner_start
        - ckb_miner_stop

    - name: Install And Configure CKB Benchmark Via Ansible-CKB-Benchmark
      include_role:
        name: ansible-ckb-benchmark
        public: false
      tags:
        - ckb_benchmark_setup
        - ckb_benchmark_install

    - name: Set Facts - `ckb_urls`
      block:
        - name: Set Facts - Declare `ckb_urls`
          set_fact:
            ckb_urls: []
        - name: Set Facts - Extend `ckb_urls`
          vars:
            ckb_port: "{{ hostvars[item].ckb_rpc_listen_address | default(ckb_rpc_listen_address) | regex_replace(\".*:\", \"\")}}"
            ckb_host: "{{ hostvars[item].ansible_host }}"
            ckb_url: "http://{{ ckb_host }}:{{ ckb_port }}"
          set_fact:
            ckb_urls: "{{ ckb_urls + [ ckb_url ] }}"
          with_items: "{{ groups.instances }}"
      tags:
        - ckb_benchmark_prepare
        - ckb_benchmark_start

    # NOTE: It seems bug that when uses `include_role` inside block statement,
    #       tags cannot pass through properly. So please do not put
    #       `include_role` inside block statement.
    - name: Start CKB Benchmark
      vars:
        ckb_benchmark_rpc_urls: "{{ ckb_urls }}"
      include_role:
        name: ansible-ckb-benchmark
        public: false
      tags:
        - ckb_benchmark_prepare
        - ckb_benchmark_start

    - name: Fetch CKB Benchmark Logfiles
      become: true
      fetch:
        flat: true
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      with_items:
        - { src: "/var/lib/ckb-benchmark/data/ckb-bench.json", dest: "ckb-bench.json" }
        - { src: "/var/lib/ckb-benchmark/data/ckb-bench.log", dest: "ckb-bench.log" }
        - { src: "/var/lib/ckb-benchmark/data/ckb-bench.brief.md", dest: "ckb-bench.brief.md" }
      tags:
        - process_result


    - name: Update and upgrade apt packages
      become: true
      become_method: sudo
      apt:
         upgrade: 'yes'
         update_cache: yes
      tags:
         - apt_update

    - name: Install prerequisites
      become: true
      become_method: sudo
      apt:
        name: ['libpq-dev', 'python3-psycopg2']
        state: latest
        install_recommends: yes
        update_cache: yes
      tags:
        - apt_install_python_packages

